name = "op-item-db-api"
main = "src/index.ts"
compatibility_date = "2025-09-18"

[vars]
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""
SUPABASE_SERVICE_ROLE_KEY = ""

# Optional: KV cache (erst im Dashboard anlegen und IDs eintragen)
# kv_namespaces = [
#   { binding = "CACHE", id = "<KV_NAMESPACE_ID>" }
# ]
